FROM golang:1.19.9-alpine

ENV APP_ENVIRONMENT=DEVELOPMENT
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
ENV PATH="/go/bin:${PATH}"

WORKDIR /app

RUN apk update && \
    apk add --no-cache make git ca-certificates

RUN go install golang.org/x/tools/gopls@v0.12.0
RUN go install github.com/swaggo/swag/cmd/swag@v1.16.1
RUN go install github.com/vektra/mockery/v2@v2.16.0
RUN go install github.com/go-delve/delve/cmd/dlv@v1.21.0
RUN go install github.com/fzipp/gocyclo/cmd/gocyclo@v0.6.0
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2

COPY go.mod .
COPY go.sum .
RUN go mod download && go clean -modcache

COPY . .

RUN chmod +x Makefile

CMD ["/bin/sh"]
