// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	dto "cloud-native-dev-lab/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PokemonProvider is an autogenerated mock type for the PokemonProvider type
type PokemonProvider struct {
	mock.Mock
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *PokemonProvider) GetByName(ctx context.Context, name string) (*dto.Pokemon, error) {
	ret := _m.Called(ctx, name)

	var r0 *dto.Pokemon
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Pokemon); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPokemonProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewPokemonProvider creates a new instance of PokemonProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPokemonProvider(t mockConstructorTestingTNewPokemonProvider) *PokemonProvider {
	mock := &PokemonProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
